Adding support for retrieving a product listing
electrumpayments/airtime-service-interface pull request #60
Opened 2020-08-21 09:54 UTC by eon

2020-08-28 09:08 UTC, TimElectrum requested changes
Perfunctory comments:
- Please check for unused imports
- We will need to add tests for the new operations and models. (I think) we have some useful ones in the base API you can extend so take a look there and feel free to chat if it's not clear.
- don't forget to update the POM, README.md and release notes.

My broader comment though is that this adds a new operation with a new way to return a list of products. Sure, it's a `List` of `ProductListing` objects which is a tuple of `Product` and a `List` of `ChannelProductListing` objects. But, conceptually, we're actually providing a list of products which isn't a new idea. We already provide a list of eligible products in response to a `lookupMsisdn` call and I think it'd be unfortunate if that existing operation missed out on the `ChannelProductListing` enhancement.

What about:

1. Add a `List<ChannelProductListing>` as a property of `Product`.
2. Drop the idea of a `ProductListing`. This really just ties the `List<ChannelProductListing>` to the associated `Product`. If the `List<ChannelProductListing>`is _within_ the `Product` then we don't need the `ProductListing` model.
3. Instead of the `listProducts` operation returning a new `ProductListingResponse` model, we simply return a `List<Product>`. 

This wouldn't _add_ to the new operation but the two benefits I like are:

1. Fewer new models to manage.
2. Existing lists of products get the benefit too.

You might need to update the `lookupMsisdn` operation to accept a new optional `channelName` parameter.

2020-08-28 09:41 UTC, eon commented on src/main/java/io/electrum/airtime/api/model/ChannelProductListing.java
> +   @JsonProperty(value = "channelName", required = true)
I would imagine that adding it to the JsonProperty would also make it mandatory during (de)serialization, while the ApiModelProperty will only affect the swagger. Happy to go with the convention.

2020-08-28 09:42 UTC, eon commented on src/main/java/io/electrum/airtime/api/model/ChannelProductListing.java
> +import com.fasterxml.jackson.annotation.JsonProperty;
My objective here was really just to get to down to the point of having a swagger to distribute, but noted

2020-08-28 10:08 UTC, eon commented on src/main/java/io/electrum/airtime/api/model/ChannelProductListing.java
> +   private String productDisplayCategory = null;
Do you have suggestions? As long as it can be passed through from ui all the way down I wouldn't want to be too prescriptive

2020-08-28 10:12 UTC, eon commented on src/main/java/io/electrum/airtime/api/model/ChannelProductListing.java
> +   private Integer productDisplaySortOrder = null;
ok

2020-08-28 10:18 UTC, eon commented on src/main/java/io/electrum/airtime/api/model/ChannelProductListing.java
> +   @ApiModelProperty(value = "A sort order that is meaningful for display purposes.")
Is a bit of a weird one, not entirely sure how to word much better.

2020-08-28 11:56 UTC, eon commented
> Perfunctory comments:
> 
> * Please check for unused imports
> * We will need to add tests for the new operations and models. (I think) we have some useful ones in the base API you can extend so take a look there and feel free to chat if it's not clear.
> * don't forget to update the POM, README.md and release notes.

Cool, cool, will do - this was just a quick draft to nail the API.

> My broader comment though is that this adds a new operation with a new way to return a list of products. Sure
> 
> * it's a `List` of `ProductListing` objects
>   
>   * which is a tuple of
>     
>     * `Product`
>     * a `List` of `ChannelProductListing` objects.
> 
> But, conceptually, we're just providing a list of products which isn't a new idea in our API. We already provide a list of eligible products in response to a `lookupMsisdn` call and I think it'd be unfortunate if that existing operation missed out on the `ChannelProductListing` enhancement.
> 
> What about:
> 
> 1. Add a `List<ChannelProductListing>` as a property of `Product`.
> 2. Drop the idea of a `ProductListing`. This really just ties the `List<ChannelProductListing>` to the associated `Product`. If the `List<ChannelProductListing>`is _within_ the `Product` then we don't need the `ProductListing` model.
> 3. Instead of the `listProducts` operation returning a new `ProductListingResponse` model, we simply return a `List<Product>`.
> 
> This wouldn't _add_ to the new operation but the two benefits I like are:
> 
> 1. Fewer new models to manage.
> 2. Existing lists of products get the benefit too.
> 
> You might need to update the `lookupMsisdn` operation to accept a new optional `channelName` parameter.

Sounds good, will do.

2020-09-03 13:10 UTC, TimElectrum reviewed
make sure you update from master because there's been another release

2020-09-03 13:10 UTC, TimElectrum commented on src/main/java/io/electrum/airtime/api/model/ChannelProductListing.java
> +   private String productDisplayCategory = null;
Limit it to 50 characters? I know that some names get quite long - I blame marketing departments

2020-09-03 13:10 UTC, TimElectrum commented on src/main/java/io/electrum/airtime/api/model/Product.java
>     @Override
any particular reason not to update the `hashCode` method?

2020-09-03 13:10 UTC, TimElectrum commented on src/test/java/io/electrum/vas/api/TestAirtimeApiResourceClasses.java
> +                {ProductsResourceTestClass.class, "getProductsImpl", IProductsResourceTestImpl.class, "getProductsImpl"},
interesting - I think @gevashkar-rampersadh added a new operation (`trialPurchase`) and struggled with testing it like this because it returns HTTP 501. Maybe check in with him and see if either of you are missing something.

2020-09-03 13:10 UTC, TimElectrum commented on src/test/java/io/electrum/airtime/api/ModelsTest.java
>  public class ModelsTest {
I think I added a `NewModelsTest` class either to the base API or one of the other APIs. It's got a bunch of these standard tests (serialise, deserialise, serialise/deserialise, validation etc.) and then you would just need to update data providers.

You're covering everything we need I think so not too phased

2020-09-03 13:39 UTC, eon commented on src/main/java/io/electrum/airtime/api/model/Product.java
>     @Override
does stupidity count?

2020-09-03 13:54 UTC, eon commented on src/test/java/io/electrum/vas/api/TestAirtimeApiResourceClasses.java
> +                {ProductsResourceTestClass.class, "getProductsImpl", IProductsResourceTestImpl.class, "getProductsImpl"},
I added a new resource class, so I'm really just adding this test to catch future regressions. Not 100% sure if I should include an implemented method or use the default, but it works either way

2020-09-03 14:33 UTC, TimElectrum approved these changes

2020-09-03 18:09 UTC, merged