Added VOICE_BUNDLE productType and VOUCHER_STATUS_UNKNOWN errorType
electrumpayments/airtime-service-interface pull request #64
Opened 2020-10-14 11:31 UTC by simone-van-zyl

2020-10-14 11:56 UTC, RichardFourie commented on pom.xml
> +    <minor-version>19</minor-version>
Don't forget about the version number in the readme.

2020-10-14 11:57 UTC, RichardFourie commented on src/docs/devguide/hugo/site/content/release-notes.md
>  Released TBD
Seems like someone forgot to update the date for the previous version.

2020-10-14 12:26 UTC, simone-van-zyl commented on pom.xml
> +    <minor-version>19</minor-version>
Changed the readme =)

2020-10-14 12:26 UTC, simone-van-zyl commented on src/docs/devguide/hugo/site/content/release-notes.md
>  Released TBD
Fixed it according to git commit date for final release of v5.18.0

2020-10-14 13:45 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/model/ErrorDetail.java
> +      OUTCOME_UNKNOWN("OUTCOME_UNKNOWN");
Changed after discussion with @TimElectrum

2020-10-14 19:16 UTC, RichardFourie approved these changes
Remember to update the date and then you can release.

2020-10-14 20:13 UTC, TimElectrum requested changes
please also update the `ordinalDataProvider` data provider in the `io.electrum.airtime.api.NewModelTest`

2020-10-14 20:16 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +- Added new `ProductType`, `VOICE_BUNDLE`,  and new `ErrorType`, `OUTCOME_UNKNOWN`.
also, the rapidly changing emphasis/spacing/font for each word in this sentence makes my eyes go weird. And one bullet point makes it look like you did one thing. Hows about:
```suggestion
- Added a new `ProductType` called `VOICE_BUNDLE`.
- Added a new `ErrorType` called `OUTCOME_UNKNOWN`.
```

2020-10-16 06:52 UTC, TimElectrum approved these changes

2020-10-16 07:14 UTC, merged