Feature sender msisdn
electrumpayments/airtime-service-interface pull request #74
Opened 2022-02-28 14:07 UTC by sahnsookyung

2022-03-04 06:21 UTC, simone-van-zyl requested changes
Good job @sahnsookyung 
Just a few small changes.
We're also missing some release notes and tests here.
- Release notes are under `airtime-service-interface/src/docs/devguide/hugo/site/content/release-notes.md`
- You should add some new model tests for your new code - we can have a chat in person about how those work =)

2022-03-04 06:21 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/IMsisdnResource.java
>     default void lookupMsisdn(
@sahnsookyung Do you understand why we make this default and not just public like the very first constructor in this class?

2022-03-04 06:21 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/MsisdnResource.java
> +         @ApiParam(value = "The sender Msisdn. This must conform to the ITU E.164 numbering plan (https://www.itu.int/rec/T-REC-E.164/en).", required = false) @QueryParam(LookupMsisdn.QueryParameters
"The sender Msisdn" Is a bit vague for someone using our api for the first time trying to figure out the difference between the senderMSISDN and the msisdn fields. Maybe add a bit more description here. Remember this is client facing.

2022-03-04 06:21 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +   public MsisdnInfoResponse senderMsisdn(Msisdn senderMsisdn) {
Some copy pasting here. Give this a good javadoc to describe the sender =)

2022-03-04 06:21 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +   }
copy pasta

2022-03-04 06:21 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +      sb.append("    senderMsisdn: ").append(Utils.toIndentedString(senderMsisdn)).append('\n');
remember to update the equals and hashcode methods too!

2022-03-04 09:25 UTC, sahnsookyung commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +      sb.append("    senderMsisdn: ").append(Utils.toIndentedString(senderMsisdn)).append('\n');
Updated

2022-03-04 09:26 UTC, sahnsookyung commented on src/main/java/io/electrum/airtime/api/IMsisdnResource.java
>     default void lookupMsisdn(
The first one also seems to be default (no modifier), please could you point me?

2022-03-04 09:34 UTC, sahnsookyung commented on src/main/java/io/electrum/airtime/api/MsisdnResource.java
> +         @ApiParam(value = "The sender Msisdn. This must conform to the ITU E.164 numbering plan (https://www.itu.int/rec/T-REC-E.164/en).", required = false) @QueryParam(LookupMsisdn.QueryParameters
Added the following description:
The senderMsisdn is the msisdn of the person (sponsor) who buys airtime for a receiver.

2022-03-04 09:35 UTC, sahnsookyung commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +   public MsisdnInfoResponse senderMsisdn(Msisdn senderMsisdn) {
Gave description as before

2022-03-04 09:41 UTC, sahnsookyung commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +   }
copy pasta!

2022-03-07 21:18 UTC, simone-van-zyl commented on pom.xml
> +    <patch-version>0-RC4</patch-version>
reminder to finalise

2022-03-07 21:18 UTC, simone-van-zyl commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Release 4 March 2022
Date and version reminder

2022-03-07 21:18 UTC, simone-van-zyl commented on src/docs/devguide/hugo/site/content/release-notes.md
> +- Added sender MSISDN. The senderMsisdn is the MSISDN of the sponsor, who buys airtime for a receiver.
```suggestion
- Added an optional `senderMSISDN` path parameter to the lookupMSISDN call. The senderMsisdn is the MSISDN of the sponsor, who buys airtime for a receiver.
```

2022-03-07 21:18 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +   public MsisdnInfoResponse senderMsisdn(Msisdn senderMsisdn) {
So the sender is not the one that necessarily get's looked up. For the purpose of the airtime product the sender is the msisdn from which the request originated.

2022-03-07 21:18 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +   @JsonProperty("senderMsisdn")
```suggestion
   @ApiModelProperty(value = "The msisdn from which the request originated.")
   @JsonProperty("senderMsisdn")
```

2022-03-07 21:18 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/IMsisdnResource.java
>     default void lookupMsisdn(
This class is an interface, all methods are implicitly public unless specified otherwise. We make subsequent constructors default for backwards compatibility. Remember that all the public methods of an interface must be implemented by child classes. To avoid updating all the class that implement this interface we use the default modifier =)

2022-03-07 21:19 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/MsisdnResource.java
> +         @ApiParam(value = "The sender Msisdn. This must conform to the ITU E.164 numbering plan (https://www.itu.int/rec/T-REC-E.164/en).", required = false) @QueryParam(LookupMsisdn.QueryParameters
The sender is not necessarily the sponsor. It is however the originator of the request.

2022-03-07 21:20 UTC, simone-van-zyl requested changes
Some more comments

2022-03-07 21:20 UTC, simone-van-zyl commented
We also need to update the snippet in the readme with the new versions. 
<img width="599" alt="image" src="https://user-images.githubusercontent.com/52028676/157119748-736da957-1fcd-4132-b356-778a1579b2fd.png">

2022-03-07 21:25 UTC, simone-van-zyl commented
Reminder about those tests for coverage

2022-03-09 08:22 UTC, sahnsookyung commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Release 4 March 2022
Is this a reminder to update the date/version once finalized?

2022-03-09 08:25 UTC, sahnsookyung commented on src/main/java/io/electrum/airtime/api/IMsisdnResource.java
>     default void lookupMsisdn(
Thanks for the explanation!

2022-03-14 10:35 UTC, simone-van-zyl requested changes
1 change

2022-03-14 10:35 UTC, simone-van-zyl commented on pom.xml
> +    <patch-version>0-RC3</patch-version>
reminder to final

2022-03-14 10:35 UTC, simone-van-zyl commented on src/main/java/io/electrum/airtime/api/model/MsisdnInfoResponse.java
> +    * @param senderMsisdn "The MSISDN from which the request originated."
```suggestion
    * @param senderMsisdn The MSISDN from which the request originated.
```

2022-03-14 10:39 UTC, simone-van-zyl approved these changes

2022-03-14 11:00 UTC, simone-van-zyl approved these changes

2022-03-14 11:58 UTC, merged