Feature/error detail implements i error detail
electrumpayments/airtime-service-interface pull request #75
Opened 2022-04-20 14:56 UTC by willie84

Kindly review the implementation  of IErrorDetail so that we can do a final release.

2022-06-01 07:32 UTC, Shaaheen requested changes
- Needs some tests. Can probably add in the https://github.com/electrumpayments/airtime-service-interface/blob/master/src/test/java/io/electrum/airtime/api/ModelsTest.java
- Please update release notes with what changes you made including the service interface bump that you did as that was quite a hefty jump (10 minor versions)

2022-06-01 07:32 UTC, Shaaheen commented on pom.xml
> +    <patch-version>0-RC3</patch-version>
final

2022-06-01 07:32 UTC, Shaaheen commented on pom.xml
> +    <service-interface-base-version>3.39.0-RC4</service-interface-base-version>
final

2022-06-01 07:32 UTC, Shaaheen commented on src/main/java/io/electrum/airtime/api/model/ErrorDetail.java
> +      this.errorType = ErrorType.valueOf(s);
name variable a bit better, rather than `s` - probably name `errorTypeAsString`

2022-06-03 14:32 UTC, VeeneshJeena commented on pom.xml
> +    <patch-version>0-RC3</patch-version>
remember to finalise

2022-06-03 14:33 UTC, VeeneshJeena commented on release-notes.md
> +## Version 5.26.0-RC3 - 03 June 2022
finalise the version

2022-06-03 14:34 UTC, VeeneshJeena commented on src/main/java/io/electrum/airtime/api/model/ErrorDetail.java
> +      this.errorType = ErrorType.valueOf(errorTypeFromString);
```suggestion
   public void setErrorTypeFromString(String errorTypeAsString) throws Exception {
      this.errorType = ErrorType.valueOf(errorTypeAsString);
```

2022-06-03 14:34 UTC, VeeneshJeena commented on src/main/java/io/electrum/airtime/api/model/ErrorDetail.java
> +    * Implemented from IErrorDetail interfaces.
This Javadoc is incorrect. This should document what this method does.

2022-06-03 14:35 UTC, VeeneshJeena requested changes
small changes required

2022-06-06 07:09 UTC, VeeneshJeena commented on release-notes.md
> +## Version 5.26.1 - 03 June 2022
version number is incorrect, It should be 5.26.0.
Update the date to today's date.

2022-06-06 07:11 UTC, VeeneshJeena commented on src/main/java/io/electrum/airtime/api/model/ErrorDetail.java
> +    * Implemented from IErrorDetail where the errorType is passed string and the value is evaluated from the Enum.
```suggestion
    * Converts an errorType from a String representation to the enum equivalent.
```

2022-06-06 07:12 UTC, VeeneshJeena requested changes
some small comments

2022-06-06 09:49 UTC, willie84 commented
v5.26.0 [release-type final]

2022-06-06 09:50 UTC, merged